---
Description: >
   template for Strands Chainlit app as AWS LightSail service

Parameters:

  Name:
    Type: String
    Default: 'strands-chainlit'

  ChainlitAppRoot:
    Type: String
    Default: '/tmp'

  # update secret (the value below is fake) with your own if you use advanced security Chainlit beyond (username, password)
  ChainlitAuthSecret:
    Type: String
    Default: '3q7.s1>zk*PRG46E,uip@03qOXY0CvCq.vuztOA7^-JuInv2l2hPv1TnfuV5bJzv'

  ChainlitHost:
    Type: String
    Default: '0.0.0.0'

  ChainlitPort:
    Type: String
    Default: '8888'

  ChainlitDebug:
    Type: String
    Default: 'True'

  # see for pricing: https://aws.amazon.com/lightsail/pricing/
  LightSailPower:
    Type: String
    Default: 'small'

  # it is recommended not to copy/paste your IAM credentials directly in here. 'resolve:ssm:etc.' allows reading them directly from SSM.
  AwsAccessKeyId:
    Type: String
    Default: '{{resolve:ssm:strands-lightsail-aws-access-key-id:1}}'

  AwsSecretAccessKey:
    Type: String
    Default: '{{resolve:ssm:strands-lightsail-aws-secret-access-key:1}}'

  ImageTag:
    Type: String
    Default: 'latest'

  ImageRegistry:
    Type: String
    Default: 'didierdurand'

Resources:

  StrandsChainlitContainer:
    Type: AWS::Lightsail::Container
    DeletionPolicy: Delete
    Properties:
      ServiceName: !Sub '${Name}-${UnicitySuffix.Value}'
      ContainerServiceDeployment:
        Containers:
            - ContainerName: !Sub '${Name}-container-${UnicitySuffix.Value}'
              Environment:
                # env var used by config.py::load_config to read file config.toml
                - Variable: 'CHAINLIT_APP_ROOT'
                  Value: !Ref ChainlitAppRoot
                - Variable: 'CHAINLIT_AUTH_SECRET'
                  Value: !Ref ChainlitAuthSecret
                - Variable: 'CHAINLIT_HOST'
                  Value: !Ref ChainlitHost
                - Variable: 'CHAINLIT_PORT'
                  Value: !Ref ChainlitPort
                - Variable: 'CHAINLIT_DEBUG'
                  Value: !Ref ChainlitDebug
                - Variable: 'AWS_ACCESS_KEY_ID'
                  Value: !Ref AwsAccessKeyId
                - Variable: 'AWS_SECRET_ACCESS_KEY'
                  Value: !Ref AwsSecretAccessKey
              Image: !Sub '${ImageRegistry}/${Name}:${ImageTag}'
              Ports:
                - Port: !Ref ChainlitPort
                  Protocol: 'HTTP'
        PublicEndpoint:
          ContainerName: !Sub '${Name}-container-${UnicitySuffix.Value}'
          ContainerPort: !Ref ChainlitPort
          HealthCheckConfig:
            HealthyThreshold: 2
            IntervalSeconds: 5
            Path: '/'
            SuccessCodes: '200'
            TimeoutSeconds: 2
            UnhealthyThreshold: 2
      IsDisabled: 'false'
      Power: !Ref LightSailPower
      Scale: 1
      Tags:
        - Key: 'Name'
          Value: !Sub '${Name}-${UnicitySuffix.Value}'

  UnicitySuffix:
    Type: AWS::SSM::Parameter
    DeletionPolicy: Delete
    Properties:
      Type: String
      Name: !Join
        - '-'
        - - !Sub 'unicity-suffix-lightsail-${Name}'
          - !Select [ 0, !Split [ '-', !Select [ 2, !Split [ /, !Ref AWS::StackId ] ] ] ]
      Value: !Select [ 0, !Split [ '-', !Select [ 2, !Split [ /, !Ref AWS::StackId ] ] ] ]
      Tags:
        Key: 'Name'
        Value: !Sub '${Name}-${AWS::StackId}'
