name: 'build docker image'

on:

  workflow_dispatch:  # Allow manual triggering

  push:
    paths:
      - 'Dockerfile'
      - '.github/workflows/build_docker.yaml'
      - '.hadolint.yaml'
      - 'requirements.txt'
      - 'src/**'

jobs:

  build_docker:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      BASE_REPO: 'strands-serverless'
      DOCKER_FILE: 'Dockerfile'
      DOCKER_TAGS: 'didierdurand/strands-chainlit:latest'

    steps:

      - name: 'checkout git code'
        uses: actions/checkout@v4

      - name: 'prelude'
        run: |
          printenv

      - name: 'log in to Docker Hub'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 'check docker setup'
        run: |
          docker --version
          docker image ls

      - name: 'lint docker file'
        run: |
          # https://github.com/hadolint/hadolint
          docker run --rm -i -v ${PWD}/.hadolint.yaml:/.config/hadolint.yaml hadolint/hadolint < ${{env.DOCKER_FILE}}

      - name: 'set up Docker Buildx'
        uses: docker/setup-buildx-action@v3

      - name: 'build and push image to Docker Hub'
        if: github.repository == 'strands-serverless'
        uses: docker/build-push-action@v6
        with:
          push: true
          file: ${{ env.DOCKER_FILE }}
          tags: ${{ env.DOCKER_TAGS }}

      - name: 'check created docker image'
        run: |
          docker image ls